###

POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Diana Raquel Cruz Cruz",
    "dui": "00133121",
    "email": "00133121@uca.edu.sv",
    "phone": "+503 71668439",
    "address": "UCA",
    "password": "root",
    "role": "admin"
}

###

GET http://localhost:9000/api/users HTTP/1.1

###

GET http://localhost:9000/api/users/635380520e4f82e2cf36860c HTTP/1.1

###
PUT http://localhost:9000/api/users/635380520e4f82e2cf36860c HTTP/1.1
Content-Type: application/json

{
    "name": "Douglas Mauricio Cabrera Pineda",
    "age": 20,
    "email": "douglascabrera.dev@gmail.com"
}

###
DELETE http://localhost:9000/api/users/636494bb69685ec088f98fd9 HTTP/1.1